/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserRegisterRouteImport } from './routes/user.register'
import { Route as UserLoginRouteImport } from './routes/user.login'
import { Route as UserDashboardRouteImport } from './routes/user.dashboard'
import { Route as AuthorityRegisterRouteImport } from './routes/authority.register'
import { Route as AuthorityLoginRouteImport } from './routes/authority.login'
import { Route as AuthorityDashboardRouteImport } from './routes/authority.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRegisterRoute = UserRegisterRouteImport.update({
  id: '/user/register',
  path: '/user/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/user/login',
  path: '/user/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRegisterRoute = AuthorityRegisterRouteImport.update({
  id: '/authority/register',
  path: '/authority/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityLoginRoute = AuthorityLoginRouteImport.update({
  id: '/authority/login',
  path: '/authority/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityDashboardRoute = AuthorityDashboardRouteImport.update({
  id: '/authority/dashboard',
  path: '/authority/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/login': typeof AuthorityLoginRoute
  '/authority/register': typeof AuthorityRegisterRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/login': typeof UserLoginRoute
  '/user/register': typeof UserRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/login': typeof AuthorityLoginRoute
  '/authority/register': typeof AuthorityRegisterRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/login': typeof UserLoginRoute
  '/user/register': typeof UserRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/login': typeof AuthorityLoginRoute
  '/authority/register': typeof AuthorityRegisterRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/login': typeof UserLoginRoute
  '/user/register': typeof UserRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authority/dashboard'
    | '/authority/login'
    | '/authority/register'
    | '/user/dashboard'
    | '/user/login'
    | '/user/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authority/dashboard'
    | '/authority/login'
    | '/authority/register'
    | '/user/dashboard'
    | '/user/login'
    | '/user/register'
  id:
    | '__root__'
    | '/'
    | '/authority/dashboard'
    | '/authority/login'
    | '/authority/register'
    | '/user/dashboard'
    | '/user/login'
    | '/user/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorityDashboardRoute: typeof AuthorityDashboardRoute
  AuthorityLoginRoute: typeof AuthorityLoginRoute
  AuthorityRegisterRoute: typeof AuthorityRegisterRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserLoginRoute: typeof UserLoginRoute
  UserRegisterRoute: typeof UserRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/register': {
      id: '/user/register'
      path: '/user/register'
      fullPath: '/user/register'
      preLoaderRoute: typeof UserRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/login': {
      id: '/user/login'
      path: '/user/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/register': {
      id: '/authority/register'
      path: '/authority/register'
      fullPath: '/authority/register'
      preLoaderRoute: typeof AuthorityRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/login': {
      id: '/authority/login'
      path: '/authority/login'
      fullPath: '/authority/login'
      preLoaderRoute: typeof AuthorityLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/dashboard': {
      id: '/authority/dashboard'
      path: '/authority/dashboard'
      fullPath: '/authority/dashboard'
      preLoaderRoute: typeof AuthorityDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorityDashboardRoute: AuthorityDashboardRoute,
  AuthorityLoginRoute: AuthorityLoginRoute,
  AuthorityRegisterRoute: AuthorityRegisterRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserLoginRoute: UserLoginRoute,
  UserRegisterRoute: UserRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
